name: Run Tabular Data Processor

on:
  push:
    branches:
      - github-action-test

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tabular_data/requirements.txt

    # Step 4: Run the script
    - name: Run processor.py script
      run: |
        python tabular_data/processor.py

    # Step 5: Configure git user (needed to push back changes)
    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    # Step 6: Commit the generated output files
    - name: Commit output files
      run: |
        git add tabular_data/output
        git commit -m "Add test generated output file" || echo "No changes to commit"

    # Step 7: Push the changes back to the 'github-action-test' branch
    - name: Push changes to github-action-test
      run: |
        git push origin github-action-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}